# Uncomment the next line to define a global platform for your project
platform :ios, '17.0'

target 'SocialSignIn' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SocialSignIn
  pod 'GoogleSignIn'
  pod 'GoogleSignInSwiftSupport'

end
